services:
  agromach-server:
    image: ghcr.io/userver-framework/ubuntu-22.04-userver-pg:latest
    platform: linux/amd64
    privileged: true
    volumes:
      - ./backend:/backend:rw
    ports:
      - "8080:8080"
    working_dir: /backend
    environment:
      - USERVER_ENABLE_STACK_USAGE_MONITOR=0
    command: >
      bash -c "
      mkdir -p build-debug && cd build-debug && 
      cmake .. -DCMAKE_BUILD_TYPE=Debug && 
      make -j$(nproc) && 
      ./agromach_backend --config ../configs/static_config.yaml
      "
  agromach-frontend:
    image: node:20-slim
    container_name: agromach-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npx vite --host"
    depends_on:
      - agromach-server